name: example

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s -H Metadata:true 'http://169.254.169.254/metadata/instance?api-version=2021-02-01' | jq -r '.compute.location'
